
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractInstanceWithAddress, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import MultiSigContractArtifactJson from '../target/MultiSig-MultiSig.json' with { type: 'json' };
export const MultiSigContractArtifact = loadContractArtifact(MultiSigContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract MultiSig;
 */
export class MultiSigContract extends ContractBase {
  
  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, MultiSigContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, MultiSigContract.artifact, wallet) as Promise<MultiSigContract>;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, initial_signers: AztecAddressLike[], initial_signer_count: (bigint | number), initial_threshold: (bigint | number), wormhole_address: AztecAddressLike) {
    return new DeployMethod<MultiSigContract>(PublicKeys.default(), wallet, MultiSigContractArtifact, MultiSigContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, initial_signers: AztecAddressLike[], initial_signer_count: (bigint | number), initial_threshold: (bigint | number), wormhole_address: AztecAddressLike) {
    return new DeployMethod<MultiSigContract>(publicKeys, wallet, MultiSigContractArtifact, MultiSigContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof MultiSigContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<MultiSigContract['methods'][M]>
  ) {
    return new DeployMethod<MultiSigContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      MultiSigContractArtifact,
      MultiSigContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return MultiSigContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(MultiSigContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'signers' | 'threshold' | 'signer_count' | 'wormhole_address' | 'proposals' | 'next_proposal_id'> {
      return {
        signers: {
      slot: new Fr(1n),
    },
threshold: {
      slot: new Fr(2n),
    },
signer_count: {
      slot: new Fr(3n),
    },
wormhole_address: {
      slot: new Fr(4n),
    },
proposals: {
      slot: new Fr(5n),
    },
next_proposal_id: {
      slot: new Fr(6n),
    }
      } as ContractStorageLayout<'signers' | 'threshold' | 'signer_count' | 'wormhole_address' | 'proposals' | 'next_proposal_id'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(initial_signers: array, initial_signer_count: integer, initial_threshold: integer, wormhole_address: struct) */
    constructor: ((initial_signers: AztecAddressLike[], initial_signer_count: (bigint | number), initial_threshold: (bigint | number), wormhole_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** execute_proposal(proposal_id: field) */
    execute_proposal: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_next_proposal_id() */
    get_next_proposal_id: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal(proposal_id: field) */
    get_proposal: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_executed(proposal_id: field) */
    get_proposal_executed: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_operation_type(proposal_id: field) */
    get_proposal_operation_type: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_proposal_signature_count(proposal_id: field) */
    get_proposal_signature_count: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_signer_count() */
    get_signer_count: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_threshold() */
    get_threshold: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_wormhole_address() */
    get_wormhole_address: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** is_signer(address: struct) */
    is_signer: ((address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** propose_add_signer(new_signer: struct) */
    propose_add_signer: ((new_signer: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** propose_change_threshold(new_threshold: integer) */
    propose_change_threshold: ((new_threshold: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** propose_execute_transaction(token: struct, recipient: struct, amount: field) */
    propose_execute_transaction: ((token: EthAddressLike, recipient: EthAddressLike, amount: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** propose_remove_signer(signer_to_remove: struct) */
    propose_remove_signer: ((signer_to_remove: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sign_proposal(proposal_id: field) */
    sign_proposal: ((proposal_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
